# Generated by Django 3.2.7 on 2021-09-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=200)),
                ('env_budget', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('env_funds', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_date', models.DateTimeField(verbose_name='transaction date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('recipient', models.CharField(max_length=200)),
                ('env_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envelopeBudgeting.envelope')),
            ],
        ),
    ]
