# Generated by Django 3.2.7 on 2021-09-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelopeBudgeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='env_id',
            new_name='env',
        ),
    ]
